### ISSUE TITLE
workflow does not work

### ISSUE THREAD

**Issue by cage1016** [yedhrab/FlaticonAlfred#1]
```bash
[19:02:33.706] Flat Icon[Script Filter] Queuing argument 'page'
[19:02:34.379] Flat Icon[Script Filter] Script with argv '(null)' finished
[19:02:34.381] ERROR: Flat Icon[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/kaichuchung/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.80B24BC1-F65A-4B6C-A97D-974644A67C49/main.py", line 4, in <module>
    from flaticon import Client as FlatIconClient
  File "/Users/kaichuchung/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.80B24BC1-F65A-4B6C-A97D-974644A67C49/flaticon/__init__.py", line 1, in <module>
    from .client import Client
  File "/Users/kaichuchung/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.80B24BC1-F65A-4B6C-A97D-974644A67C49/flaticon/client.py", line 7, in <module>
    from utils.tools import download
  File "/Users/kaichuchung/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.80B24BC1-F65A-4B6C-A97D-974644A67C49/utils/tools.py", line 7, in <module>
    async def download(url: str, filepath: str | Path, session: ClientSession) -> Path:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

as above error show. It does not work as gif show.

**Comment by yedhrab** [comment]
Let me fix it (:

**Comment by yedhrab** [comment]
Fixed
